In [2]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df.head())

   order_id customer_id        order_time     delivery_time  order_value  \
0      2001        C101  2023-08-01 18:00  2023-08-01 18:45        500.0
1      2002        C102  2023-08-01 19:00  2023-08-01 18:50        700.0
2      2003        C103  2023/08/02 20:00               NaN          NaN
3      2004        C104           invalid  2023-08-03 21:00        800.0
4      2005        C105  2023-08-04 18:30  2023-08-04 19:00       -200.0

  payment_method restaurant  rating
0            upi    Dominos       4
1    Credit card        KFC       5
2     Debit Card  McDonalds       3
3            UPI    Dominos       6
4           Cash        KFC       2

In [20]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df.head())
df.info()
df.isnull().sum()
df.duplicated().sum()
import pandas as pd
df=pd.read_csv("data.csv")

   order_id customer_id        order_time     delivery_time  order_value  \
0      2001        C101  2023-08-01 18:00  2023-08-01 18:45        500.0
1      2002        C102  2023-08-01 19:00  2023-08-01 18:50        700.0
2      2003        C103  2023/08/02 20:00               NaN          NaN
3      2004        C104           invalid  2023-08-03 21:00        800.0
4      2005        C105  2023-08-04 18:30  2023-08-04 19:00       -200.0

  payment_method restaurant  rating
0            upi    Dominos       4
1    Credit card        KFC       5
2     Debit Card  McDonalds       3
3            UPI    Dominos       6
4           Cash        KFC       2
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        7 non-null      int64
 1   customer_id     7 non-null      object
 2   order_time      7 non-null      object
 3   delivery_time   6 non-null      object
 4   order_value     6 non-null      float64
 5   payment_method  6 non-null      object
 6   restaurant      7 non-null      object
 7   rating          7 non-null      int64
dtypes: float64(1), int64(2), object(5)
memory usage: 580.0+ bytes

In [25]:
df["order_time"] = pd.to_datetime(df["order_time"], errors="coerce")
df["delivery_time"] = pd.to_datetime(df["delivery_time"], errors="coerce")
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
1,2002,C102,2023-08-01 19:00:00,2023-08-01 18:50:00,700.0,Credit card,KFC,5
2,2003,C103,NaT,NaT,NaN,Debit Card,McDonalds,3
3,2004,C104,NaT,2023-08-03 21:00:00,800.0,UPI,Dominos,6
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,NaN,Pizza Hut,4

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        7 non-null      int64
 1   customer_id     7 non-null      object
 2   order_time      5 non-null      datetime64[ns]
 3   delivery_time   6 non-null      datetime64[ns]
 4   order_value     6 non-null      float64
 5   payment_method  6 non-null      object
 6   restaurant      7 non-null      object
 7   rating          7 non-null      int64
dtypes: datetime64[ns](2), float64(1), int64(2), object(3)
memory usage: 580.0+ bytes

In [31]:
df=df[df['delivery_time']>=df['order_time']]
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,NaN,Pizza Hut,4

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 6
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        4 non-null      int64
 1   customer_id     4 non-null      object
 2   order_time      4 non-null      datetime64[ns]
 3   delivery_time   4 non-null      datetime64[ns]
 4   order_value     4 non-null      float64
 5   payment_method  3 non-null      object
 6   restaurant      4 non-null      object
 7   rating          4 non-null      int64
dtypes: datetime64[ns](2), float64(1), int64(2), object(3)
memory usage: 288.0+ bytes

In [33]:
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,NaN,Pizza Hut,4

In [35]:
df['order_value']=pd.to_numeric(df['order_value'],errors='coerce')
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,NaN,Pizza Hut,4

In [38]:
df['payment_method'].fillna('unknown',inplace=True)
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,unknown,Pizza Hut,4

In [41]:
df = df[(df['rating'] >= 1) & (df['rating'] <= 5)]
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,upi,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,Cash,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,unknown,Pizza Hut,4

In [42]:
df["payment_method"] = (
    df["payment_method"]
    .str.strip()
    .str.upper()
    .str.replace(" ", "_")
)
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,UPI,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,CASH,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,CASH,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,UNKNOWN,Pizza Hut,4

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, 0 to 6
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        4 non-null      int64
 1   customer_id     4 non-null      object
 2   order_time      4 non-null      datetime64[ns]
 3   delivery_time   4 non-null      datetime64[ns]
 4   order_value     4 non-null      float64
 5   payment_method  4 non-null      object
 6   restaurant      4 non-null      object
 7   rating          4 non-null      int64
dtypes: datetime64[ns](2), float64(1), int64(2), object(3)
memory usage: 288.0+ bytes

SyntaxError: invalid decimal literal (1470501617.py, line 2)

In [47]:
df["payment_method"] = (
    df["payment_method"]
    .str.strip()
    .str.upper()
    .str.replace(r"\s+", "_", regex=True)
)
df

,order_id,customer_id,order_time,delivery_time,order_value,payment_method,restaurant,rating
0,2001,C101,2023-08-01 18:00:00,2023-08-01 18:45:00,500.0,UPI,Dominos,4
4,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,CASH,KFC,2
5,2005,C105,2023-08-04 18:30:00,2023-08-04 19:00:00,-200.0,CASH,KFC,2
6,2006,C106,2023-08-05 17:00:00,2023-08-05 17:40:00,1200.0,UNKNOWN,Pizza Hut,4