In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\mathe\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\mathe\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\mathe\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\mathe\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mathe\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\mathe\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
df=pd.read_csv("student_data.csv")
print(df.head())

  school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...
3     GP   F   15       U     GT3       T     4     2   health  services  ...
4     GP   F   16       U     GT3       T     3     3    other     other  ...

  famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0      4        3      4     1     1      3        6   5   6   6
1      5        3      3     1     1      3        4   5   5   6
2      4        3      2     2     3      3       10   7   8  10
3      3        2      2     1     1      5        2  15  14  15
4      4        3      2     1     2      5        4   6  10  10

[5 rows x 33 columns]

In [3]:
import pandas as pd
df=pd.read_csv("student_data.csv")
df.shape

(395, 33)

In [7]:
import pandas as pd
df=pd.read_csv("student_data.csv")
df.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [8]:
import pandas as pd
df=pd.read_csv("student_data.csv")
df.info

<bound method DataFrame.info of     school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   F   18       U     GT3       A     4     4   at_home   teacher
1       GP   F   17       U     GT3       T     1     1   at_home     other
2       GP   F   15       U     LE3       T     1     1   at_home     other
3       GP   F   15       U     GT3       T     4     2    health  services
4       GP   F   16       U     GT3       T     3     3     other     other
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   M   20       U     LE3       A     2     2  services  services
391     MS   M   17       U     LE3       T     3     1  services  services
392     MS   M   21       R     GT3       T     1     1     other     other
393     MS   M   18       R     LE3       T     3     2  services     other
394     MS   M   19       U     LE3       T     1     1     other   at_home

     ... famrel freetime  goout  Dalc  Walc health absences  G1  G2  G3
0    ...      4        3      4     1     1      3        6   5   6   6
1    ...      5        3      3     1     1      3        4   5   5   6
2    ...      4        3      2     2     3      3       10   7   8  10
3    ...      3        2      2     1     1      5        2  15  14  15
4    ...      4        3      2     1     2      5        4   6  10  10
..   ...    ...      ...    ...   ...   ...    ...      ...  ..  ..  ..
390  ...      5        5      4     4     5      4       11   9   9   9
391  ...      2        4      5     3     4      2        3  14  16  16
392  ...      5        5      3     3     3      3        3  10   8   7
393  ...      4        4      1     3     4      5        0  11  12  10
394  ...      3        2      3     3     3      5        5   8   9   9

[395 rows x 33 columns]>

In [12]:
import pandas as pd
df=pd.read_csv("student_data.csv")
df.sex

0      F
1      F
2      F
3      F
4      F
      ..
390    M
391    M
392    M
393    M
394    M
Name: sex, Length: 395, dtype: object

In [16]:
import pandas as pd
df=pd.read_csv("student_data.csv")
df[["sex","Fjob"]]

    sex      Fjob
0     F   teacher
1     F     other
2     F     other
3     F  services
4     F     other
..   ..       ...
390   M  services
391   M  services
392   M     other
393   M     other
394   M   at_home

[395 rows x 2 columns]

In [15]:
import pandas as pd
df=pd.read_csv("student_data.csv")
df.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [17]:
import pandas as pd
df=pd.read_csv("student_data.csv")
df.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,16.696203,2.749367,2.521519,1.448101,2.035443,0.334177,3.944304,3.235443,3.108861,1.481013,2.291139,3.554430,5.708861,10.908861,10.713924,10.415190
std,1.276043,1.094735,1.088201,0.697505,0.839240,0.743651,0.896659,0.998862,1.113278,0.890741,1.287897,1.390303,8.003096,3.319195,3.761505,4.581443
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [27]:
import pandas as pd
df = pd.read_csv("student_data.csv")
df.drop(columns=['sex'], inplace=True)
df.drop

<bound method DataFrame.drop of     school  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0       GP   18       U     GT3       A     4     4   at_home   teacher
1       GP   17       U     GT3       T     1     1   at_home     other
2       GP   15       U     LE3       T     1     1   at_home     other
3       GP   15       U     GT3       T     4     2    health  services
4       GP   16       U     GT3       T     3     3     other     other
..     ...  ...     ...     ...     ...   ...   ...       ...       ...
390     MS   20       U     LE3       A     2     2  services  services
391     MS   17       U     LE3       T     3     1  services  services
392     MS   21       R     GT3       T     1     1     other     other
393     MS   18       R     LE3       T     3     2  services     other
394     MS   19       U     LE3       T     1     1     other   at_home

     reason  ... famrel  freetime  goout  Dalc Walc health absences  G1  G2  \
0    course  ...      4         3      4     1    1      3        6   5   6
1    course  ...      5         3      3     1    1      3        4   5   5
2     other  ...      4         3      2     2    3      3       10   7   8
3      home  ...      3         2      2     1    1      5        2  15  14
4      home  ...      4         3      2     1    2      5        4   6  10
..      ...  ...    ...       ...    ...   ...  ...    ...      ...  ..  ..
390  course  ...      5         5      4     4    5      4       11   9   9
391  course  ...      2         4      5     3    4      2        3  14  16
392  course  ...      5         5      3     3    3      3        3  10   8
393  course  ...      4         4      1     3    4      5        0  11  12
394  course  ...      3         2      3     3    3      5        5   8   9

     G3
0     6
1     6
2    10
3    15
4    10
..   ..
390   9
391  16
392   7
393  10
394   9

[395 rows x 32 columns]>