In [1]:
import pandas as pd
df=pd.read_csv("tested.csv")
print(df.head())

   PassengerId  Survived  Pclass  \
0          892         0       3
1          893         1       3
2          894         0       2
3          895         0       3
4          896         1       3

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                     Myles, Mr. Thomas Francis    male  62.0      0      0
3                              Wirz, Mr. Albert    male  27.0      0      0
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1

    Ticket     Fare Cabin Embarked
0   330911   7.8292   NaN        Q
1   363272   7.0000   NaN        S
2   240276   9.6875   NaN        Q
3   315154   8.6625   NaN        S
4  3101298  12.2875   NaN        S

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [3]:
df['Age'].fillna(df['Age'].median(), inplace=True)
df

C:\Users\mathe\AppData\Local\Temp\ipykernel_13236\432742771.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,27.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,27.0,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,27.0,1,1,2668,22.3583,NaN,C

In [20]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,0,34.5,0,0,7.8292,1
1,893,1,3,1,47.0,1,0,7.0000,2
2,894,0,2,0,62.0,0,0,9.6875,1
3,895,0,3,0,27.0,0,0,8.6625,2
4,896,1,3,1,22.0,1,1,12.2875,2
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,27.0,0,0,8.0500,2
414,1306,1,1,1,39.0,0,0,108.9000,0
415,1307,0,3,0,38.5,0,0,7.2500,2
416,1308,0,3,0,27.0,0,0,8.0500,2
417,1309,0,3,0,27.0,1,1,22.3583,0

In [5]:
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",0,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",1,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",0,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",0,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",1,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",0,27.0,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",1,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",0,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",0,27.0,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",0,27.0,1,1,2668,22.3583,NaN,C

In [7]:
df['Embarked'] = df['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",0,34.5,0,0,330911,7.8292,NaN,NaN
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",1,47.0,1,0,363272,7.0000,NaN,NaN
2,894,0,2,"Myles, Mr. Thomas Francis",0,62.0,0,0,240276,9.6875,NaN,NaN
3,895,0,3,"Wirz, Mr. Albert",0,27.0,0,0,315154,8.6625,NaN,NaN
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",1,22.0,1,1,3101298,12.2875,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",0,27.0,0,0,A.5. 3236,8.0500,NaN,NaN
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",1,39.0,0,0,PC 17758,108.9000,C105,NaN
415,1307,0,3,"Saether, Mr. Simon Sivertsen",0,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,NaN
416,1308,0,3,"Ware, Mr. Frederick",0,27.0,0,0,359309,8.0500,NaN,NaN
417,1309,0,3,"Peter, Master. Michael J",0,27.0,1,1,2668,22.3583,NaN,NaN

In [8]:
df.drop(['Cabin', 'Name', 'Ticket'], axis=1, inplace=True)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,0,34.5,0,0,7.8292,NaN
1,893,1,3,1,47.0,1,0,7.0000,NaN
2,894,0,2,0,62.0,0,0,9.6875,NaN
3,895,0,3,0,27.0,0,0,8.6625,NaN
4,896,1,3,1,22.0,1,1,12.2875,NaN
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,27.0,0,0,8.0500,NaN
414,1306,1,1,1,39.0,0,0,108.9000,NaN
415,1307,0,3,0,38.5,0,0,7.2500,NaN
416,1308,0,3,0,27.0,0,0,8.0500,NaN
417,1309,0,3,0,27.0,1,1,22.3583,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Sex          418 non-null    int64
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Fare         417 non-null    float64
 8   Embarked     0 non-null      float64
dtypes: float64(3), int64(6)
memory usage: 29.5 KB

In [12]:
df['Fare'] = df['Fare'].fillna(df['Fare'].median())
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,0,34.5,0,0,7.8292,NaN
1,893,1,3,1,47.0,1,0,7.0000,NaN
2,894,0,2,0,62.0,0,0,9.6875,NaN
3,895,0,3,0,27.0,0,0,8.6625,NaN
4,896,1,3,1,22.0,1,1,12.2875,NaN
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,27.0,0,0,8.0500,NaN
414,1306,1,1,1,39.0,0,0,108.9000,NaN
415,1307,0,3,0,38.5,0,0,7.2500,NaN
416,1308,0,3,0,27.0,0,0,8.0500,NaN
417,1309,0,3,0,27.0,1,1,22.3583,NaN

In [14]:
df2 = pd.read_csv("tested.csv")

df['Embarked'] = df2['Embarked']
df

     PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch      Fare Embarked
0            892         0       3    0  34.5      0      0    7.8292        Q
1            893         1       3    1  47.0      1      0    7.0000        S
2            894         0       2    0  62.0      0      0    9.6875        Q
3            895         0       3    0  27.0      0      0    8.6625        S
4            896         1       3    1  22.0      1      1   12.2875        S
..           ...       ...     ...  ...   ...    ...    ...       ...      ...
413         1305         0       3    0  27.0      0      0    8.0500        S
414         1306         1       1    1  39.0      0      0  108.9000        C
415         1307         0       3    0  38.5      0      0    7.2500        S
416         1308         0       3    0  27.0      0      0    8.0500        S
417         1309         0       3    0  27.0      1      1   22.3583        C

[418 rows x 9 columns]

In [15]:
df['Embarked'] = df['Embarked'].fillna(df['Embarked'].mode()[0])

df['Embarked'] = df['Embarked'].map({'C': 0, 'Q': 1, 'S': 2})
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,0,34.5,0,0,7.8292,1
1,893,1,3,1,47.0,1,0,7.0000,2
2,894,0,2,0,62.0,0,0,9.6875,1
3,895,0,3,0,27.0,0,0,8.6625,2
4,896,1,3,1,22.0,1,1,12.2875,2
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,27.0,0,0,8.0500,2
414,1306,1,1,1,39.0,0,0,108.9000,0
415,1307,0,3,0,38.5,0,0,7.2500,2
416,1308,0,3,0,27.0,0,0,8.0500,2
417,1309,0,3,0,27.0,1,1,22.3583,0

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Sex          418 non-null    int64
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Fare         418 non-null    float64
 8   Embarked     418 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 29.5 KB

In [18]:
df.drop_duplicates(inplace=True)
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,0,34.5,0,0,7.8292,1
1,893,1,3,1,47.0,1,0,7.0000,2
2,894,0,2,0,62.0,0,0,9.6875,1
3,895,0,3,0,27.0,0,0,8.6625,2
4,896,1,3,1,22.0,1,1,12.2875,2
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,27.0,0,0,8.0500,2
414,1306,1,1,1,39.0,0,0,108.9000,0
415,1307,0,3,0,38.5,0,0,7.2500,2
416,1308,0,3,0,27.0,0,0,8.0500,2
417,1309,0,3,0,27.0,1,1,22.3583,0

In [19]:
df.isnull().sum()
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,892,0,3,0,34.5,0,0,7.8292,1
1,893,1,3,1,47.0,1,0,7.0000,2
2,894,0,2,0,62.0,0,0,9.6875,1
3,895,0,3,0,27.0,0,0,8.6625,2
4,896,1,3,1,22.0,1,1,12.2875,2
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,27.0,0,0,8.0500,2
414,1306,1,1,1,39.0,0,0,108.9000,0
415,1307,0,3,0,38.5,0,0,7.2500,2
416,1308,0,3,0,27.0,0,0,8.0500,2
417,1309,0,3,0,27.0,1,1,22.3583,0

In [21]:
df.columns = df.columns.str.strip().str.lower()
df

,passengerid,survived,pclass,sex,age,sibsp,parch,fare,embarked
0,892,0,3,0,34.5,0,0,7.8292,1
1,893,1,3,1,47.0,1,0,7.0000,2
2,894,0,2,0,62.0,0,0,9.6875,1
3,895,0,3,0,27.0,0,0,8.6625,2
4,896,1,3,1,22.0,1,1,12.2875,2
...,...,...,...,...,...,...,...,...,...
413,1305,0,3,0,27.0,0,0,8.0500,2
414,1306,1,1,1,39.0,0,0,108.9000,0
415,1307,0,3,0,38.5,0,0,7.2500,2
416,1308,0,3,0,27.0,0,0,8.0500,2
417,1309,0,3,0,27.0,1,1,22.3583,0

In [22]:
df['age'] = df['age'].fillna(df['age'].median()).astype(int)
df

     passengerid  survived  pclass  sex  age  sibsp  parch      fare  embarked
0            892         0       3    0   34      0      0    7.8292         1
1            893         1       3    1   47      1      0    7.0000         2
2            894         0       2    0   62      0      0    9.6875         1
3            895         0       3    0   27      0      0    8.6625         2
4            896         1       3    1   22      1      1   12.2875         2
..           ...       ...     ...  ...  ...    ...    ...       ...       ...
413         1305         0       3    0   27      0      0    8.0500         2
414         1306         1       1    1   39      0      0  108.9000         0
415         1307         0       3    0   38      0      0    7.2500         2
416         1308         0       3    0   27      0      0    8.0500         2
417         1309         0       3    0   27      1      1   22.3583         0

[418 rows x 9 columns]

In [23]:
df = df[df['age'] > 0]
df

     passengerid  survived  pclass  sex  age  sibsp  parch      fare  embarked
0            892         0       3    0   34      0      0    7.8292         1
1            893         1       3    1   47      1      0    7.0000         2
2            894         0       2    0   62      0      0    9.6875         1
3            895         0       3    0   27      0      0    8.6625         2
4            896         1       3    1   22      1      1   12.2875         2
..           ...       ...     ...  ...  ...    ...    ...       ...       ...
413         1305         0       3    0   27      0      0    8.0500         2
414         1306         1       1    1   39      0      0  108.9000         0
415         1307         0       3    0   38      0      0    7.2500         2
416         1308         0       3    0   27      0      0    8.0500         2
417         1309         0       3    0   27      1      1   22.3583         0

[413 rows x 9 columns]

In [27]:
df.to_csv("cleaned_data.csv", index=False)
df

     passengerid  survived  pclass  sex  age  sibsp  parch      fare  embarked
0            892         0       3    0   34      0      0    7.8292         1
1            893         1       3    1   47      1      0    7.0000         2
2            894         0       2    0   62      0      0    9.6875         1
3            895         0       3    0   27      0      0    8.6625         2
4            896         1       3    1   22      1      1   12.2875         2
..           ...       ...     ...  ...  ...    ...    ...       ...       ...
413         1305         0       3    0   27      0      0    8.0500         2
414         1306         1       1    1   39      0      0  108.9000         0
415         1307         0       3    0   38      0      0    7.2500         2
416         1308         0       3    0   27      0      0    8.0500         2
417         1309         0       3    0   27      1      1   22.3583         0

[413 rows x 9 columns]